version: "3.9"
services:
  db:
    image: postgres
    container_name: pg_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dotacodex
    ports:
      - "5432:5432"
    restart: unless-stopped
  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_NAME: db
      PGADMIN_SERVER_HOST: db
      PGADMIN_SERVER_PORT: 5432
    ports:
      - 5050:80